apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-test
  namespace: apptest
  labels:
    release: prometheus-monitoring
spec:
  groups:
    - name: app.rules
      rules:
        - alert: MuitasRequisicoes
          expr: rate(app_requests_total[1m]) > 5
          for: 1m
          labels:
            severity: warning
          annotations:
            summary: "Muitas requisições na aplicação"
            description: "A aplicação está recebendo muitas requisições"
